/**
 * @fileoverview gRPC-Web generated client stub for auth
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.0
// source: auth.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as auth_pb from './auth_pb'; // proto import: "auth.proto"


export class AuthServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorAuth = new grpcWeb.MethodDescriptor(
    '/auth.AuthService/Auth',
    grpcWeb.MethodType.UNARY,
    auth_pb.AuthRequest,
    auth_pb.AuthResponse,
    (request: auth_pb.AuthRequest) => {
      return request.serializeBinary();
    },
    auth_pb.AuthResponse.deserializeBinary
  );

  auth(
    request: auth_pb.AuthRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_pb.AuthResponse>;

  auth(
    request: auth_pb.AuthRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_pb.AuthResponse) => void): grpcWeb.ClientReadableStream<auth_pb.AuthResponse>;

  auth(
    request: auth_pb.AuthRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_pb.AuthResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.AuthService/Auth',
        request,
        metadata || {},
        this.methodDescriptorAuth,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.AuthService/Auth',
    request,
    metadata || {},
    this.methodDescriptorAuth);
  }

}

