/**
 * @fileoverview gRPC-Web generated client stub for world
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.0
// source: world.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as world_pb from './world_pb'; // proto import: "world.proto"


export class WorldServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetWorld = new grpcWeb.MethodDescriptor(
    '/world.WorldService/GetWorld',
    grpcWeb.MethodType.UNARY,
    world_pb.GetWorldRequest,
    world_pb.GetWorldResponse,
    (request: world_pb.GetWorldRequest) => {
      return request.serializeBinary();
    },
    world_pb.GetWorldResponse.deserializeBinary
  );

  getWorld(
    request: world_pb.GetWorldRequest,
    metadata?: grpcWeb.Metadata | null): Promise<world_pb.GetWorldResponse>;

  getWorld(
    request: world_pb.GetWorldRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: world_pb.GetWorldResponse) => void): grpcWeb.ClientReadableStream<world_pb.GetWorldResponse>;

  getWorld(
    request: world_pb.GetWorldRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: world_pb.GetWorldResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/world.WorldService/GetWorld',
        request,
        metadata || {},
        this.methodDescriptorGetWorld,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/world.WorldService/GetWorld',
    request,
    metadata || {},
    this.methodDescriptorGetWorld);
  }

}

