// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "auth.proto" (package "auth", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuthService } from "./auth";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AuthResponse } from "./auth";
import type { AuthRequest } from "./auth";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service auth.AuthService
 */
export interface IAuthServiceClient {
    /**
     * OAuth認証
     * レスポンスのlocationにリダイレクトすることでOAuth認証を行う
     *
     * @generated from protobuf rpc: Auth(auth.AuthRequest) returns (auth.AuthResponse);
     */
    auth(input: AuthRequest, options?: RpcOptions): UnaryCall<AuthRequest, AuthResponse>;
}
/**
 * @generated from protobuf service auth.AuthService
 */
export class AuthServiceClient implements IAuthServiceClient, ServiceInfo {
    typeName = AuthService.typeName;
    methods = AuthService.methods;
    options = AuthService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * OAuth認証
     * レスポンスのlocationにリダイレクトすることでOAuth認証を行う
     *
     * @generated from protobuf rpc: Auth(auth.AuthRequest) returns (auth.AuthResponse);
     */
    auth(input: AuthRequest, options?: RpcOptions): UnaryCall<AuthRequest, AuthResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthRequest, AuthResponse>("unary", this._transport, method, opt, input);
    }
}
